name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout source
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup JDK (for Maven)
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    # Bump version (create file if missing)
    - name: Bump patch version
      id: bump
      run: |
        VERSION_FILE=VERSION
        if [ ! -f "$VERSION_FILE" ]; then
          echo "1.0.0" > $VERSION_FILE
        fi
        VERSION=$(cat $VERSION_FILE)
        IFS='.' read -r major minor patch <<< "$VERSION"
        patch=$((patch+1))
        NEW_VERSION="$major.$minor.$patch"
        echo $NEW_VERSION > $VERSION_FILE
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

    # Commit new version
    - name: Commit new version
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add VERSION
        git commit -m "Bump version to ${{ steps.bump.outputs.new_version }}" || echo "No changes to commit"
        git push

    # Build JAR with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Login to Docker Hub
    - name: Log in to Docker registry
      uses: docker/login-action@v3
      with:
        username: guycoff
        password: 784951623Atnt

    - name: Build & push image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: docker.io/guycoff/simple-java-maven-app:1.0.3
